### ISSUE TITLE
Problematic Entrez ID

### ISSUE THREAD

**Issue by cthoyt** [indralab/protmapper#30]
The GNAS gene (https://www.ncbi.nlm.nih.gov/gene/2778) seems to make protmapper upset. Try the following code:

```python
from protmapper.uniprot_client import get_gene_name, get_id_from_entrez
entrez_id = '2778'
uniprot_id = get_id_from_entrez(entrez_id)
assert 'O95467, P63092, P84996, Q5JWF2' == uniprot_id

# The following line will cause an http.client.InvalidURL to be raised, since this UniProt accession is not right
get_gene_name(uniprot_id)
```

**Comment by bgyori** [comment]
I see -- this is not a pretty design choice but what happens here is that since there is a one-to-many mapping from the GNAS gene to corresponding proteins, the `get_id_from_entrez` function returns a list of UniProt IDs as a single string joined by `, `. It is up to the caller to process this string (check for `, `, split, etc.) and figure out how to handle one-to-many mappings. Calling `get_gene_name` with `O95467, P63092, P84996, Q5JWF2` first does a local dict lookup with the given ID, which fails, and then naively calls the UniProt web service with the ID, which of course also fails.

**Comment by cthoyt** [comment]
muahaha the central dogma strikes back!

**Comment by cthoyt** [comment]
Would you consider returning a list instead of a string in a situation like this? Or would that make the implementation ugly and slow?

**Comment by bgyori** [comment]
Unfortunately at this point, it would be pretty painful to change the return type - for consistency, it would involve changing a lot of other conversion functions that are very heavily used in INDRA and other code bases. So as a user, your best bet is to call `get_id_from_entrez`, and if you need to make subsequent calls to other functions taking a UniProt ID, check for `,` in the string and split it as necessary.

**Comment by cthoyt** [comment]
Fair enough. I'd say this issue could be closed without change. Alternatively, you could do a try/catch around the type of error I got and return a custom one that gives a bit more context and maybe links users to this issue.
